// <auto-generated> Adjusted to match database schema for Identity compatibility. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAKKE_NEWS_API.Models;

public partial class News
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime PublicationDate { get; set; }

    public int CountryId { get; set; }

    public int CategoryId { get; set; }

    public string AuthorId { get; set; }

    public string ImagePath { get; set; }

    public virtual User Author { get; set; }

    public virtual Category Category { get; set; }

    public virtual Country Country { get; set; }
}