// <auto-generated> Adjusted to match database schema for Identity compatibility. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAKKE_NEWS_API.Models;

public partial class User
{
    public string Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public string NormalizedUserName { get; set; }

    public string NormalizedEmail { get; set; }

    public virtual ICollection<News> News { get; set; } = new List<News>();
}